/* tslint:disable */
/* eslint-disable */
/**
 * Tikitok Norge API
 * Dette er en komplett OpenAPI 3.1-spesifikasjon for en TikTok-lignende app.  **Omfang** - **Klient/Frontend-API**: Endepunkter som brukes av mobil- og webklienter (autentisering, feed, videoer, kommentarer, likes, følgerelasjoner, søk, varsler, opplasting m.m.). - **Backend/Admin-API**: Moderasjon, innholdsflagg, overstyringer, metrikker og backoffice-jobber. - **Webhooks**: Hendelser sendt til tredjepart-/interne konsumenter.  **Konvensjoner** - Versjonering via URL (`/v1`) og `X-API-Version` header. - Cursor-basert paginering med `next_cursor` og `prev_cursor`. - Alle tidsstempler i ISO 8601 (UTC). - Feil følger RFC 9457-lignende struktur. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

